### ISSUE TITLE
New features under development

### ISSUE THREAD

**Issue by artmg** [lkollar/pywarmup#2]
Hi László,

This is a very polished looking repo - I'm impressed!

I have joined up with a couple of others who are interested in continuing [alex-103](https://github.com/alex-0103)'s work. We are beginning to extend the functionality available to python users of the Warmup API, and I thought you might be interested in knowing as we add features. We are also building a useful knowledge store for the API in the [wiki](https://github.com/ha-warmup/warmup/wiki).

For now they are in the standalone [warmup4ie/warmup4ie.py](https://github.com/ha-warmup/warmup/blob/master/warmup_cc/warmup4ie/warmup4ie.py) file - however we are keen to bring the [PyPI package](https://pypi.org/project/warmup4ie/) up to date with new features by the time we deliver our integration into the main Home Assistant core code.

I am not sure in what context you are using your pywarmup, but I hope there might be something in these updates could be of interest to you. Feel free to reach out with questions. 

All the best, Art

**Comment by lkollar** [comment]
Hey! I was planning on uploading this to PyPI as I'm using this in the Home Assistant integration I built. I found the warmup4ie repo when I was trying to set my thermostat up in HA, but due to changes in Home Assistant's API the custom component did not work anymore so I decided to build a new integration based on warmup4ie.

The HA integration I built supports basic functionality: setting and displaying temperature, turning off and on and displaying program mode. However, it did not seem to properly register the thermostat as a device in the device registry and I have not added support for a few other features like holiday mode and measuring power consumption. I did not have much time in the last few weeks to continue the work, but I will upload the HA integration somewhere, and if I get some time in the next few days I can try to get it in a shape so that I can open a PR in Home Assistant. I will upload `pywarmup` to PyPI as well.

**Comment by artmg** [comment]
It's great news that you have these plans - perhaps there may be opportunities to collaborate. Feel free to share what you have and give us a shout on our [issues list](https://github.com/ha-warmup/warmup/issues) for anything.

Also, do check out the linked code above for the `"method": "setOverride"` syntax in the **set_override** function - a very useful feature in these winter months.

We are in the position without an entry in the device registry, but that might be 'by design' as the only devices in there are ones created by the User via UI. Check the [dev docs](https://developers.home-assistant.io/docs/en/device_registry_index.html#defining-devices), especially the highlighted link on Config Entries, also mentioned in [this post](https://community.home-assistant.io/t/how-to-add-devices-to-device-registry/160537/2?u=artmg)

**Comment by lkollar** [comment]
@artmg I've uploaded the package to PyPI: https://pypi.org/project/pywarmup/

The branch for the HA integration is [here](https://github.com/lkollar/home-assistant/tree/warmup), but it will need a bit of cleanup before submitting the PR to Home Assistant.

**Comment by artmg** [comment]
great progress @lkollar - when it comes to [developing documentation](https://developers.home-assistant.io/docs/en/documentation_create_page.html) there may be some useful writings in our wiki pages on [Device Attributes](https://github.com/ha-warmup/warmup/wiki/Device-attributes) and [Config ideas](https://github.com/ha-warmup/warmup/wiki/Configuration-ideas). If you want some help with something please shout
